<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Yes' => 'Да',
    'No' => 'Нет',
    'Change' => 'Изменить',
    'Never' => 'Никогда',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить данный объект?',
    'Create' => 'Создать',
    'Create User' => 'Добавить Пользователя',
    'Delete' => 'Удалить',
    'Expired At' => 'Действителен до',
    'ID' => 'ID',
    'Reset' => 'Очистить',
    'Search' => 'Поиск',
    'Token' => 'Токен',
    'Update' => 'Изменить',
    'Update {modelClass}: ' => 'Изменить {modelClass}: ',
    'Update: ' => 'Изменить: ',
    'User' => 'Пользователь',
    'Users' => 'Пользователи',
    'About' => 'О Нас',
    'Contact' => 'Контакты',
    'Verification Code' => 'Код Проверки',
    'Name' => 'Имя',
    'Subject' => 'Тема',
    'Body' => 'Сообщение',
    'Submit' => 'Отправить',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => "Если у вас есть деловые предложения или другие вопросы, свяжитесь с нами с помощью этой формы.<br> Спасибо за сотрудничество",
    'Signup' => 'Регистрация',
    'Login' => 'Войти',
    'Logout' => 'Выйти',
    'Home' => 'Главная',
    'Comment' => 'Коментарий',
    'Role Name' => 'Название Роли',
    'Roles' => 'Роли',
    'Countries' => 'Страны',
    'Moderators' => 'Модераторы',
    'Options' => 'Опции',
    'Change access' => 'Смена доступа',
    'Create Role' => 'Добавить роль',
    'Username' => 'Имя Пользователя',
    'Status' => 'Статус',
    'Created' => 'Создано',
    'Updated' => 'Обновлено',
    'Congratulations' => 'Поздравляем',
    'Admin' => 'Админ',
    'Profile' => 'Профиль',
    'Welcome' => 'Добро пожаловать',
    'Photo' => 'Фото',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Благодарим Вас за обращение к нам. Мы ответим Вам как можно скорее.',
    'Shop' => 'Магазин',
    'Goods Category' => 'Категории товаров',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Properties' => 'Характеристики',
    'Price Money' => 'Цена в долларах',
    'Price Chips' => 'Цена в фишках',
    'Dollar' => 'Доллар',
    'Chip' => 'Фишка',
    'Statistic' => 'Статистика',
    'Balance' => 'Баланс',
    'Black List' => 'Черный Список',
    'Close' => 'Закрыть',
    'Update Balance' => 'Изменить Баланс',
    'Are you sure?' => 'Вы уверены?',
    ###################################

    ######################################
    // USER
    'Last Login at' => 'Время последнего входа',
    'User photo' => 'Фото пользователя',
    'Country' => 'Страна',
    'Created at' => 'Время регистрации',
    'Undefined' => 'Нет данных',
    'Guest' => 'Гость',
    'Online' => 'В сети',
    'Enter Type' => 'Тип Входа',
    'Role' => 'Роль',
    'Administrator' => 'Администратор',
    'Moderator' => 'Модератор',
    'Update role for: ' => 'Изменить роль для: ',
    'Withdrawal Requests' => 'Запросы на вывод',
    ######################################
    // STAT
    'All Games' => 'Сыгранных игр',
    'Won Games' => 'Выигранных игр',
    'AMOUNT' => 'СУММА',
    ######################################
    // ADMIN
    'Service' => 'Служебное',
    'Courses' => 'Курсы',
    'Settings' => 'Настройки',
    'Settings Name' => 'Название',
    'Refresh cash' => 'Очистить кеш',
    'Back to site' => 'Вернуться на сайт',
    'Commission, %' => 'Комиссия, %',
    'Commission' => 'Комиссия',
    'Value' => 'Значение',
    'Measurement' => 'е.и.',
    'Advert' => 'Объявление',
    'Push-notification' => 'Push-сообщения',

];
